export const lngCodeToLanguage : {[key:string] : string} = {
  cmn: 'Mandarin Chinese',
  spa: 'Spanish',
  eng: 'English',
  rus: 'Russian',
  arb: 'Standard Arabic',
  ben: 'Bengali',
  hin: 'Hindi',
  por: 'Portuguese',
  ind: 'Indonesian',
  jpn: 'Japanese',
  fra: 'French',
  deu: 'German',
  jav: 'Javanese',
  kor: 'Korean',
  tel: 'Telugu',
  vie: 'Vietnamese',
  mar: 'Marathi',
  ita: 'Italian',
  tam: 'Tamil',
  tur: 'Turkish',
  urd: 'Urdu',
  guj: 'Gujarati',
  pol: 'Polish',
  ukr: 'Ukrainian',
  kan: 'Kannada',
  mai: 'Maithili',
  mal: 'Malayalam',
  pes: 'Iranian Persian',
  mya: 'Burmese',
  swh: 'Swahili',
  sun: 'Sundanese',
  ron: 'Romanian',
  pan: 'Panjabi',
  bho: 'Bhojpuri',
  amh: 'Amharic',
  hau: 'Hausa',
  fuv: 'Nigerian Fulfulde',
  bos: 'Bosnian',
  hrv: 'Croatian',
  nld: 'Dutch',
  srp: 'Serbian',
  tha: 'Thai',
  ckb: 'Central Kurdish',
  yor: 'Yoruba',
  uzn: 'Northern Uzbek',
  zlm: 'Malay',
  ibo: 'Igbo',
  npi: 'Nepali (individual language)',
  ceb: 'Cebuano',
  skr: 'Saraiki',
  tgl: 'Tagalog',
  hun: 'Hungarian',
  azj: 'North Azerbaijani',
  sin: 'Sinhala',
  koi: 'Komi-Permyak',
  ell: 'Modern Greek',
  ces: 'Czech',
  mag: 'Magahi',
  run: 'Rundi',
  bel: 'Belarusian',
  plt: 'Plateau Malagasy',
  qug: 'Chimborazo Highland Quichua',
  mad: 'Madurese',
  nya: 'Nyanja',
  zyb: 'Yongbei Zhuang',
  pbu: 'Northern Pashto',
  kin: 'Kinyarwanda',
  zul: 'Zulu',
  bul: 'Bulgarian',
  swe: 'Swedish',
  lin: 'Lingala',
  som: 'Somali',
  hms: 'Southern Qiandong Miao',
  hnj: 'Hmong Njua',
  ilo: 'Iloko',
  kaz: 'Kazakh',
  uig: 'Uighur (Arabic)',
  hat: 'Haitian',
  khm: 'Khmer',
  prs: 'Dari',
  hil: 'Hiligaynon',
  sna: 'Shona',
  tat: 'Tatar',
  xho: 'Xhosa',
  hye: 'Armenian',
  min: 'Minangkabau',
  afr: 'Afrikaans',
  lua: 'Luba-Lulua',
  sat: 'Santali',
  bod: 'Tibetan',
  tir: 'Tigrinya',
  fin: 'Finnish',
  slk: 'Slovak',
  tuk: 'Turkmen',
  dan: 'Danish',
  nob: 'Norwegian Bokmål',
  suk: 'Sukuma',
  als: 'Tosk Albanian',
  sag: 'Sango',
  nno: 'Norwegian Nynorsk',
  heb: 'Hebrew',
  mos: 'Mossi',
  tgk: 'Tajik',
  cat: 'Catalan',
  sot: 'Southern Sotho',
  kat: 'Georgian',
  bcl: 'Central Bikol',
  glg: 'Galician',
  lao: 'Lao',
  lit: 'Lithuanian',
  umb: 'Umbundu',
  tsn: 'Tswana',
  vec: 'Venetian',
  nso: 'Pedi',
  ban: 'Balinese',
  bug: 'Buginese',
  knc: 'Central Kanuri',
  kng: 'Koongo',
  ibb: 'Ibibio',
  lug: 'Ganda',
  ace: 'Achinese',
  bam: 'Bambara',
  tzm: 'Central Atlas Tamazight',
  ydd: 'Eastern Yiddish',
  kmb: 'Kimbundu',
  lun: 'Lunda',
  shn: 'Shan',
  war: 'Waray (Philippines)',
  dyu: 'Dyula',
  wol: 'Wolof',
  kir: 'Kirghiz',
  nds: 'Low German',
  fuf: 'Pular',
  mkd: 'Macedonian',
  vmw: 'Makhuwa',
  zgh: 'Standard Moroccan Tamazight',
  ewe: 'Ewe',
  khk: 'Halh Mongolian',
  slv: 'Slovenian',
  ayr: 'Central Aymara',
  bem: 'Bemba (Zambia)',
  emk: 'Eastern Maninkakan',
  bci: 'Baoulé',
  bum: 'Bulu (Cameroon)',
  epo: 'Esperanto',
  pam: 'Pampanga',
  tiv: 'Tiv',
  tpi: 'Tok Pisin',
  ven: 'Venda',
  ssw: 'Swati',
  nyn: 'Nyankole',
  kbd: 'Kabardian',
  iii: 'Sichuan Yi',
  yao: 'Yao',
  lvs: 'Standard Latvian',
  quz: 'Cusco Quechua',
  src: 'Logudorese Sardinian',
  rup: 'Macedo-Romanian',
  sco: 'Scots',
  tso: 'Tsonga',
  men: 'Mende (Sierra Leone)',
  fon: 'Fon',
  nhn: 'Central Nahuatl',
  dip: 'Northeastern Dinka',
  kde: 'Makonde',
  snn: 'Siona',
  kbp: 'Kabiyè',
  tem: 'Timne',
  toi: 'Tonga (Zambia)',
  ekk: 'Standard Estonian',
  snk: 'Soninke',
  cjk: 'Chokwe',
  ada: 'Adangme',
  aii: 'Assyrian Neo-Aramaic',
  quy: 'Ayacucho Quechua',
  rmn: 'Balkan Romani',
  bin: 'Bini',
  gaa: 'Ga',
  ndo: 'Ndonga',
};
