apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartify-server-deployment
  labels:
    app: smartify-backend-server
spec:
  selector:
    matchLabels:
      app: smartify-backend-server
  template:
    metadata:
      labels:
        app: smartify-backend-server
    spec:
      containers:
      - name: smartify-server-container
        image: smartifyserver:v1
        resources:
          requests:
            memory: 200Mi
            cpu: 50m
          limits:
            memory: 400Mi
            cpu: 100m
        ports:
        - containerPort: 8000
          name: backend-port
        envFrom:
        - secretRef:
            name: smartify-server-secret 
        - configMapRef:
            name: smartify-server-config


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartify-client-deployment
  labels:
    app: smartify-client
spec:
  selector:
    matchLabels:
      app: smartify-client
  template:
    metadata:
      labels:
        app: smartify-client
    spec:
      containers:
      - name: smartify-client-container
        image: smartifyclient:v1
        resources:
          requests:
            memory: 200Mi
            cpu: 50m
          limits:
            memory: 400Mi
            cpu: 100m
        ports:
        - containerPort: 3000
          name: client-port
        env:                                          
        - name: REACT_APP_SERVER_URI 
          valueFrom:
            configMapKeyRef:
              name: smartify-client-config
              key: REACT_APP_SERVER_URI
        - name: REACT_APP_REDIRECT_URI 
          valueFrom:
            configMapKeyRef:
              name: smartify-server-config
              key: SPOTIFY_REDIRECT_URL
        - name: REACT_APP_SPOTIFY_CLIENT_ID 
          valueFrom:
            secretKeyRef:
              name: smartify-server-secret
              key: SPOTIFY_CLIENT_ID
---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartify-db-deployment
  labels:
    app: smartify-db
spec:
  selector:
    matchLabels:
      app: smartify-db
  template:
    metadata:
      labels:
        app: smartify-db
    spec:
      containers:
      - name: smartify-db-container
        image: smartifydb:v1
        resources:
          requests:
            memory: 200Mi
            cpu: 50m
          limits:
            memory: 400Mi
            cpu: 100m
        ports:
        - containerPort: 27017
          name: db-port
        env:
        - name: MONGO_INITDB_ROOT_USERNAME 
          valueFrom:
            secretKeyRef:
              name: smartify-db-secret
              key: MONGO_INITDB_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD 
          valueFrom:
            secretKeyRef:
              name: smartify-db-secret
              key: MONGO_INITDB_ROOT_PASSWORD
---


apiVersion: v1
kind: Service
metadata:
  name: smartify-backend-service
spec:
  type: LoadBalancer
  selector:
    app: smartify-backend-server
  ports:
  - protocol: TCP
    port: 8000
    targetPort: backend-port
    nodePort: 31000
---


apiVersion: v1
kind: Service
metadata:
  name: smartify-client-service
spec:
  type: LoadBalancer
  selector:
    app: smartify-client
  ports:
  - protocol: TCP
    port: 3000
    targetPort: client-port
    nodePort: 32000
---


apiVersion: v1
kind: Service
metadata:
  name: smartify-db-service
spec:
  type: NodePort
  selector:
    app: smartify-db
  ports:
  - protocol: TCP
    port: 27017
    targetPort: db-port
    nodePort: 30000
---


kind: Service
apiVersion: v1
metadata:
 name: spotify-auth
spec:
 type: ExternalName
 externalName: accounts.spotify.com
---


kind: Service
apiVersion: v1
metadata:
 name: spotify-client
spec:
 type: ExternalName
 externalName: spotify.com
---


kind: Service
apiVersion: v1
metadata:
 name: spotify-resources
spec:
 type: ExternalName
 externalName: open.spotify.com

